### ISSUE TITLE
pkgdown will have issue if logo is used

### ISSUE THREAD

**Issue by elong0527** [Merck/gsDesign2#17]
Within a system that have no connection to internet, the `logo` will result in error to build pkgdown website

https://github.com/Merck/gsDesign2/blob/main/man/figures/logo.png

**Comment by nanxstats** [comment]
I am fairly certain it is due to pkgdown wants to access `realfavicongenerator.net` to generate favicons from the logo file.

When I run `pkgdown::build_site()` and `pkgdown:::build_site_external()`:

```
-- Building favicons -----------------------------------------------------------
Building favicons with realfavicongenerator.net...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: realfavicongenerator.net
Error: callr subprocess failed: Could not resolve host: realfavicongenerator.net
Type .Last.error.trace to see where the error occurred
```

The solution is simple:

- Run pkgdown on a machine that can access that website
- This will generate the favicons in `/pkgdown/favicon/`
- Ignore this folder in `.Rbuildignore` using a `^pkgdown$` line
- Push the files to the repo
- Let the no-internet machines run pkgdown

@elong0527 is this "solution" reasonable?

**Comment by nanxstats** [comment]
This can be closed after https://github.com/Merck/gsDesign2/pull/18 is merged.
