### ISSUE TITLE
Location of functions for root solving [lower priority] 

### ISSUE THREAD

**Issue by fb-elong** [Merck/gsDesign2#235]
Place to discuss comments in #229

>I would appreciate it if you could make one small update: moving their function definitions outside of the exported functions.

**Comment by nanxstats** [comment]
Following the discussion today: the reason that the inner function is harder to move outside the outer function: the inner function is using variables outside of it's scope but within the outer function's scope. To move it out, additional arguments need to be added.

**Comment by elong0527** [comment]
Removed my assignment as no short-term plan to complete it.

**Comment by nanxstats** [comment]
@jdblischak do you mind helping with this when you got some time? Not urgent.

The goal is to move the inline functions `event_diff()` and `get_combo_power()` out of the upper-level function:

https://github.com/Merck/gsDesign2/blob/24fdc779a555056ecad2ef019cb455e887e51abb/R/expected_time.R#L110

https://github.com/Merck/gsDesign2/blob/4917d25086c4355d40ed455e6be21fe8d32cc8b3/R/gs_design_combo.R#L194

They are used in `uniroot()` calls.

This would drastically improve the rigorousness of these functions, because currently they used variables not defined in the function signature, thus R will search for those variables in upper level environments, which is considered dangerous. Defining them outside would enforce all invoked variables properly defined in the function signature. This would also avoid these being repeatedly redefined every time the upper-level functions are called which can be a performance hog.

**Comment by jdblischak** [comment]
`event_diff()` was straightforward, so I started with it. See #312

I'm a bit more cautious about `get_combo_power()` because the call to `uniroot()` in `gs_design_combo()` is more complex. It allows passing arguments via `...` in the top-level function signature all the way to `mvtnorm::pmvnorm()` via the `uniroot()` call

https://github.com/Merck/gsDesign2/blob/59e8a0315394a32d7437cab503da14b536fe1e1b/R/gs_design_combo.R#L26
https://github.com/Merck/gsDesign2/blob/59e8a0315394a32d7437cab503da14b536fe1e1b/R/gs_design_combo.R#L225

However, as a quick test, I deleted the `...` from the `uniroot()` call and ran the tests. Everything passed, which means this feature isn't being tested, and thus we wouldn't know if my change broke this behavior. My plan is to write a test first. If anyone knows of a realistic use case for passing an argument to `mvtnorm::pmvnorm()`, I'd appreciate any suggestions

**Comment by nanxstats** [comment]
So `get_combo_power()` accepts `...`, and `gs_prob_combo()` also accepts `...` in the function signature. However, in the definition of `gs_prob_combo()`, `...` is not used at all.

Then it would be important to check in with the original author about the intention. Since `...` was not used, should it be deleted from all these function signatures and calls to avoid confusion?

In general, it's worthwhile to review the call chain in `gs_design_combo()`: `...` is being passed to multiple function calls. I wonder if they are all necessary - `gs_utility_combo()` seems to have the same issue as above.

**Comment by nanxstats** [comment]
Hey @elong0527 I can't recall who wrote this part, could you point us to the author to clarify the `...` usage here?

**Comment by elong0527** [comment]
I guess I am the author, agree we should avoid `...` from multiple call. 

The intention is to use `...` in the `pmvnorm_combo` function. We can check if that's the final place of using `...`, if not we can skip.

**Comment by jdblischak** [comment]
I confirmed that currently the `...` are not passed all the way to `mvtnorm::pmvnorm()`

```R
library("gsDesign2")
debugonce(mvtnorm::pmvnorm)
gs_design_combo(seed = 1)
Browse[2]> print(seed)
NULL
```
