### ISSUE TITLE
standardize `test_tEvents` function

### ISSUE THREAD

**Issue by elong0527** [Merck/gsDesign2#245]
There are three test file rely on `test_tEvents` that is being defined separately but slightly different in each file. 

Please define one and only one helper function in testthat helper file.  

commit to disable those test:  https://github.com/Merck/gsDesign2/pull/243/commits/669677ab86c2bbde1b21822dd11c8fa4d0523a34

reference: https://testthat.r-lib.org/articles/special-files.html#helper-files

**Comment by LittleBeannie** [comment]
Thanks for the nice suggestion! I agree that unifying the helper function of `test_tEvents` would enhance the clarity of the code and files. If I recall correctly, Yi developed the `test_tEvents` in the maxcombo part, while someone else implemented it in the `expected_time` part. The reasons behind these slight variances remain unclear to me. Since these are separate tests, my instinct suggests that we should consult the respective testers for clarification. Moreover, I personally feel it's acceptable for different testers to have distinct testing functions, as it represents a trade-off between maintaining clean code and ensuring independent testing from individuals.

**Comment by elong0527** [comment]
It is OK to have function defined in each test file. Could we use unique function name if they do have different logic?

**Comment by LittleBeannie** [comment]
> It is OK to have function defined in each test file. Could we use unique function name if they do have different logic?

Sure thing!
