### ISSUE TITLE
[Discussion] Enable Weibull distribution for NPH design

### ISSUE THREAD

**Issue by elong0527** [Merck/gsDesign2#256]
Discussed with a gsDesign2 user, she mentioned that company may also want to use Weibull distribution for study design. 

Create a ticket for us to discuss the possibility to enable distribution in addition to piecewise exponential.

**Comment by LittleBeannie** [comment]
Decision: It is indeed a valuable idea to explore NPH distributions beyond the piecewise exponential model. However, due to the foundational structure of gsDesign2 and its reliance on the piecewise model, we will postpone the inclusion of Weibull distribution for the time being. This topic could be an intriguing area of research for summer interns, but we would require additional resources to derive the design characteristics for the Weibull distribution.
