### ISSUE TITLE
Explore optimization via SIMD and parallel

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#294]
Keaven mentioned today that some of the algorithms in gsDesign2 might benefit from GPU compute, since the logic can benefit from better vectorization or fine-grained parallel, basically the MapReduce paradigm.

## CPU SIMD

This reminds me of a potential solution via SIMD on CPUs.

- [Vector operations for accelerating expensive Bayesian computations -- a tutorial guide
](https://arxiv.org/abs/1902.09046)
- [RcppXsimd](https://cran.r-project.org/package=RcppXsimd)
- [RcppNT2](https://rcppcore.github.io/RcppNT2/)

## RcppParallel

Besides SIMD, a much simpler thing to try is [RcppParallel](https://cran.r-project.org/package=RcppParallel).

## Why

I suggest we do some research on this before going the GPU compute. These might be more realistic paths because:

1. Much better compiler support in R for C++ with CPUs than the support for Python or C++ to interface CUDA or OpenCL.
2. CPU SIMD code can still fallback to run without SIMD, while not everyone has a GPU to leverage.

These are important if we want to distribute via CRAN and have a larger audience.

**Comment by jdblischak** [comment]
I think the primary bottleneck is this call to `uniroot()`:

https://github.com/Merck/gsDesign2/blob/50067c424ab7dca4579ae895edc5de2bdcd9546e/R/expected_time.R#L122

From `?uniroot`:

> The function uniroot searches the interval from lower to upper for a root (i.e., zero) of the function f with respect to its first argument.

So this is repeatedly calling `ahr()` -> `pw_info()` -> `expected_event()` until it finds a root that satisfies the convergence tolerance. The root finding code itself is written in FORTRAN, so that is not getting any faster. Looking at the 3 nested functions that are repeatedly executed, they appear to be mostly data munging operations.

Is there someway we could parallelize `uniroot()` so that it could check multiple values along the internal simultaneously and thus converge faster? I did a quick search, but all I could find with this [SO post](https://stackoverflow.com/questions/69860570/is-there-any-faster-alternative-to-statsuniroot-function-in-r), where the user needed to parallelize many different calls to `uniroot()`, which doesn't apply to our situation.

**Comment by nanxstats** [comment]
I agree, there is little room to make root finding too much faster as that's a solved problem. The real bottleneck is probably what you identified here: evaluating the objective function repeatedly for many times. So anything that makes those functions run faster in R would be a great start, such as improving the table transformation performance.

Since in many cases these functions are written as explicit mathematical expressions, there is not an obvious way to make them faster in R. Then they are often optimized by converting into C/C++. We will see if we need to go there eventually for our case.

**Comment by nanxstats** [comment]
Discussing with Keaven reveals the focus of this issue (benefit from better vectorization or fine-grained parallel) is still about the **numerical integration**, that is, code currently written with vanilla Rcpp under `src/`.

After some research and checking the code, this feels doable. Regarding the framework, OpenMP might be a good (practical, time-tested) framework for parallelization at C/C++ level, especially when integrating with R packages. It supports SIMD construct, and can also do GPU offloading (!). Here is an interesting [guide](https://librestats.com/RparallelGuide/).

Besides the basic implementation, there will be some important engineering details to deal with, such as not using multiple threads when it's already running in a forked R process. So we probably want to talk to an expert with R/C++/OpenMP experience first if we want to move forward with this.

**Comment by nanxstats** [comment]
Before it gets too long, let's close this and continue the discussion in #321.
