### ISSUE TITLE
2 Notes from CRAN pre-test on v1.1.3

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#490]
Note 1: 
```
* checking dependencies in R code ... NOTE
Missing object imported by a ':::' call: 'simtrial:::as_gt.simtrial_gs_wlr'
```

Note 2: 
```
Examples with CPU (user + system) or elapsed time > 10s
               user system elapsed
gs_design_wlr 10.46   0.11   10.58
```

I will work on a new gsDesign2 v1.1.3 and start with the 2nd note first. 
@jdblischak, do you happen to know the reason of the 1st note?

**Comment by jdblischak** [comment]
> do you happen to know the reason of the 1st note?

Yes. We added it to the CRAN comments in #480. Do you manually build and upload the tarball, or do you use a devtools convenience function? If you are doing it manually, you need to copy-paste the contents of `cran-comments.md` into the submission comments box.

https://github.com/Merck/gsDesign2/blob/67e7423ead507be252e3282055752ba37ef95dd4/cran-comments.md?plain=1#L1-L8

Recall that according to @yihui (https://github.com/Merck/simtrial/pull/287#pullrequestreview-2328753274), CRAN allows the use of `:::` to access internal functions of another package _only_ when they have the same maintainer.

**Comment by jdblischak** [comment]
I don't think this is necessary. The class "simtrial_gs_wlr" does not exist in simtrial [0.4.1](https://github.com/Merck/simtrial/blob/v0.4.1/R/sim_gs_n.R) (the current version on CRAN). The class was added at the same time as the methods `as_gt()` and `summary()` (https://github.com/Merck/simtrial/commit/89a66570e302b248c87adc644620588046937dee). Thus there is no chance of this code path being executed if someone is running simtrial <= 0.4.1, ie since no objects have the class, there will never be S3 dispatch to this non-existent method.

**Comment by jdblischak** [comment]
Submitted `getFromNamespace()` workaround in https://github.com/Merck/gsDesign2/pull/492
